# Generated by Django 6.1.2 on 2026-10-10 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('CLIENTE', 'Cliente'), ('BARBEIRO', 'Barbeiro'), ('ADMINISTRADOR', 'Administrador')], default='CLIENTE', max_length=14),
        ),
    ]
